language: ruby
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: "--without development"
env:
  global:
  - secure: FEeS78fn/0GAwRzeUtCeqYQUzzJvZ7ZLk5SJ4ZOvsHOkHZbBClEq5kochT34A0VLDUukSUZKfSZSiuEQe00Xsv+/cZvxSKh9w/Wrn3rSWy+KesKOuq/k/R3+OBuzKn8nC5X6670i6U1FJ+z6pxUoF7KBWJPMlUEBHfys2c3uauU2OIE/Gl2Camh0v9zNiI6064SiNkygGuiZmyJkq+udzDgKN1q7dBP5DNp9f+DNl5pC+BlqB9I7h92He9la1TkRARRYbhq4qDX+oFAfXuyqNshAiMDOB6yrtMF1OPFEAsBZZ8EhnCYwno6OGGjRQFHXrZmKTpGqJd5H7xw0Qd8cjTfkM4oeteUYq/T9ZieEJqpjfHYh7o//1yy1cz15ekvtVQPY2n6S9PPfWqAH4aRlkCJ5JGQvJNG72MpS3xqyDyNuBn5BIVz3xzFTscx54yU/aoAFSFCAMfDEavD1J9FKUtTBp0Jlh2tSN9Dt0kVE6l3PDhu7Jz88xblEo93Tu6RyfXFUMov4WDa9MPnr7FbZs6LxLb6qpu/2zXIt5uEs/LzfLRz0Y5X6fyE0NYz9poekmgZkrqcn+ogfJfzEmOAV0fBcsL6faUXTazoWuCB4xmAq+2v7L3P9E57CIQarW1TVloa2SFGZVEfjwuyN430CqE26hD7Ndgg8XxhA36ebByA=
  - secure: d4WjgMtdWJ6vVCDQoMshk15hS+/c5buN61KwMbVWXhzYXusy3Am2gkWet/JlqirngSwK0Fz7OjRN5cXaOi9jJrJ2dk+x0QfD6mX41jZPiwWqGS8okWxEwwWMf9n/0n0mMAzzKfbaoDJLy7X2Z1tiz61Mi/3BILD81h3DxE/bm3koTn2zrFpwpsrqSsann0Tuoh/+Vh7/s/r9WW90u1nGzEhwOx+nEqNlN4t6eV3xnzrJ99zEwjsxmh9mWjh6GY3/UKitwQ6TnCvnelAPVEBtmUXAy1he9SdF94lG+mmRSuDm1RC31Qaz6eQOjda16FkdQHt25Pm3XSOR0jK/CHXvPvdcumM4+j3aU6uUpkyfKCmyHVjq1OBXcXnQmErEh5Fb2iQ9dpG8hwRrJqoD5eooCYQaiShcFLHtX7mKisCVNWZnunWKsMY1MfbvTHrs0FcSLVplN6+TvAekIFVuRF3VH4MrWT87dakNcrdPGAfpxEF4NjZxZtW3xi8OIl0sSJfg9OAIMzlCNnCs9stbrb0oNHg+ol+991AieRYZk98e15JR2HsKQr1wtPTppZoy47N8uZhrA7XcrnYDRgiSdbQmkwNZAsrFPqQwfEEuO1ZU6jiB/w3hB/dEaqcOP4Y9joi0y9PyQN2io/nLz/ZgIyknvxrsBwBeRUdr8XFYLzJqP3s=
