sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.6.3
  - 2.5.5
  - 2.4.6
before_install: gem install bundler -v 1.15.4
bundler_args: "--without development"
env:
  global:
  - secure: Nzc4KRt9B6ObvSaQ6s/Ec/Xb4UyDTTdlfAwFEO0elk5atuHp4J0M2VgHFVd/SsgTjFailMtxzZ9dUDwKA6yAzx2ExwDUezdtzllewYCp+/aB83Osr6Wj1xKeCFI3ZTgPK8CsIVPg60jK0IVY48iKPZ246Z6csl9acfnW2kp0I7J81UvbhVw+pC4Yu93Baaokdm+9KFizI2tNsI+HX4IXJeVSplDFbYFH22P1XWkWFNVGtBGheW7/zfAeyonjkNqIh5HlIo25jBstHyMw6H70StJWnqFRqqUWXfmsKzmzKSaV1pd6Ww1+Xz7cnk9U2iRObhEHE3NYn3f8xQioavado4WtxyiMiSzi1y1y7vbCqMkK35/ipGSp8ykK3QE/SOxOsYlBhbX3hm6m3TnuHl1bwCii/JqdJNyoLhym5PnB4WmHEp4f6/TnL1zF1P6a88N3ztgtAtSd/4815lveE03cffzNb8yroRS1SpqZnEAmKhu8aHpxko6CS09pvA9kOsSyECaQ65lML80Sgwd4LiIhOLFs4MjKCmvN0nM9DRUN8q285TeiGljW70oYSkA/xznk1eEGfPpZdsaLZe/4vh67IUzUY8OXQnyLNfxCxccPmuLmsg4J+vP7sZDN9GJzb7F9iYif5th00y1Q7TRpMIbQRIODUJB7TsSC6jqJSIO8OlA=
  - secure: cUikUP+M+dS892HZj/RuUUiD2lpsn4FK+E51Wh4lpcGO+R8Zhtr+hHxoF99j/miE8axegKmc+d/fBU2Kv/8h0xfin4GafDB2uHlkyD0uLz8c1wB6iecThSQ2VU5TkF/oWyMSfVe4RbI1VE08KHN3/k6aZcR6fVI6d0pD9VitL+LdVs+HWvw//pixsBMt36ezSmhO0K5/8p1+t8/3y8kcmiQF3GW2wrhcdrvG275RqJZVnvHIAkiGOTzCbiuZhm9qGpi8HaH5YQ+um6bJH9ocw7Uh+rLFBhQJstfxdFnwh6V97XTVst3IkuH+aWSEwoa3upEXjfnPvhcbGKtzUOfdgfNZ5HiWiCUEuYIDIoTH710JJK0FjapB/8gekomvAfx/qJkSVBvwArMFIp3jj7OBgYit+xO2wBU6j0qdWczsdKrXmtmDw02bypZF3PpaOfAr3n23JlwLK2oHt8XITOKCwnrUGPyuL8s/U94NJCoFKpV2DyuoPsOJh0DhCrPKELSL+tfrw+BkSkBF8oEUkTTE4nZ6tzN5Eku2bikWkh1i7f3ThB3iw/7XvoXuHJHZQX9RJOcr/jynEGvEXrEtrXUMpCvuk509upoCzk54d1PXOzhzzvKZWzZDD5b4VU5iWLfSuhWXw80+irnADsU1SSVEA0quNU6reSZyVdBUjLSN7do=
