sudo: false
language: ruby
rvm:
- ruby-head
- 2.4.2
- 2.3.5
- 2.2.8
- 2.1.10
before_install: gem install bundler -v 1.15.4
bundler_args: "--without development"
env:
  global:
  - secure: UvwpsFF79k0WFq9as2xWWFI4P0WfvW8Ezo0P3VNahE+89X9f+hMl/N6UdRTLOg8VkiUsourJSuRXvZx4WhjTiSLKMFk4cBzB1UVY3jWtd38uNovQuA+auS9jKiLWPt/f8y3sKQ9B6MwvheSxapDoqZU/q2kwbO0OAxF9K54/JDdsXgnZL7ERR6qCGHoaz4oB/HTVrqwDBDmwmhfXVkv+DVzw8MP6Xl7ITiY1ctgLAa1ESxqeSNVXHfTpSWqIH1AbccXqp8DLC5mROfHewmJA4k9Z2tfmH/AGyBsBrcgczSKQ4ZcM9KZLPLdaoq72cdR5i4WnTHV2xJzf46N7MCWVyL6Tn9KNiQ4FzsufAXYHQcS9ygOe9+PQErzJ/AbHoAFuJI78elOIfAOntV9TAgTPSs2Ti6NHKOp71H3UWVgGPg0LEILjC6NL5FqWBLm9wynwqwK7hG9ybxX4G73yr+0y9MQPi6EL6HMGNLOnLoNZmATYBjkp0r9exNOyDMvRPMniZgGXsL+6Qad8t8FdXwf1sBontFzQc72w+40lnBX6igU7IzPz/GN38ZDSNp9jg0ynFjP2lgk1hz4VxzWR2eIqklrEJKz8YGAXhSfkFGXvJgrbgoND6BVDHzA/XTLEhYPU6OquKBUpMj2shBK8n/AH1mXRzQTU+1l1tR573J5rHqs=
  - secure: kkGmgevkvX1hj2p2F1FbBRZkr4Bj/ibTnfUzVrdJOiGN4IxLX26eJzaSZASB9hYLug3MfF8u+vJwS1rZL3MFwQVgLcftHPTvxcQuF6VzJH6IbNyToI+nifI7z59pMYzio/7WSAegF4i1fWpAnj4w2jjmmZMDQwhdFYQnNcK/JO37Fv99YXRl4KKSS6y7BdeaMet7FMI67b5sessOctUdHVu735uRar9EPjaGR1nqW0YQjIma7cYa8QhNQ4pZrM4Vn98IfmR3EhSH5YXW/LRz8YtbqAX943KNf+S2+bRhB0MJVdlzRtBghDFmxo9XKdWEhm58Mn44Uld/tyDUB2YcfNY09kxnxS1p4SBooOraLUVaYg0VL4J7sJfiMKGFRsO03ZZRO3Z2kdgGeBdE+SEodEDwTMov8oshoo4q63VQRRDn1hoz4tkDmZAkQ6PjkpqNDRS6U67mM9kjNh+Y3I2XuTeOT6AxfTHr1+OTxFDPTIgThdmuKmSt+Qoc27QSnP84i+mbwJNxKj77zVpTsxTk81z2AWbM04hTVWVc02fuVjnAza1jRNd9TyNYj01rMNlX7b6jZ8spCcUmG9cqejQNPPhXOdAIl7QZrmiZnmNWMakcfcKRONlj9AAGVqmsStQaFGRAXUnCSa1J9ecssx/se0wwPGjMqsY+/TV4t7e0Xvc=
